//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX_Database_First
{
    using System;
    
    public enum StateNames : int
    {
        Florida = 0,
        California = 1,
        Texas = 2,
        NewYork = 3,
        Lousiana = 4
    }
}
